version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - db_password

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bankdb
      DB_USER: postgres
      DB_PASSWORD_FILE: /run/secrets/db_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      ADMIN_USER_FILE: /run/secrets/admin_user
      ADMIN_PASSWORD_FILE: /run/secrets/admin_password
    ports:
      - "8080:8080"
    secrets:
      - db_password
      - jwt_secret
      - admin_user
      - admin_password

volumes:
  postgres-data:

secrets:
  db_password:
    file: ./secrets/db_password
  jwt_secret:
    file: ./secrets/jwt_secret
  admin_user:
    file: ./secrets/admin_user
  admin_password:
    file: ./secrets/admin_password